### ISSUE TITLE
Possible collaboration

### ISSUE THREAD

**Issue by moloney** [wtclarke/pymapvbvd#13]
I'm glad to see more software for working with this data, especially in the Python space.  You inspired me to release some of my own code (https://github.com/moloney/twix/), which was based on some code in VeSPA but modified to be more efficient particularly when it comes to memory use.  I later modified it based on the Matlab "mapvbvd" code to work with the newer format.  Anyway I think the API if fairly nice, but it is probably a little bit behind in terms of features as I haven't touched it if a few years.  I am starting to ramp up some other work in this space so do plan to do more work on it in the near future, and likely use your code at least as a reference.

So this isn't really any concrete proposal, so much as I just want to open up conversation and spread some awareness. Thanks for releasing your work!

**Comment by wtclarke** [comment]
Hi @moloney,

Thanks for getting in touch. Are you also aware of @pehses https://github.com/pehses/twixtools ? I agree that it would be nice to have one twix handling library in python rather than multiple. Do you have any particular thoughts on what could be done?

**Comment by wtclarke** [comment]
I'm going to close this issue now. Feel free to reach out again if you want to chase up this idea.
