### ISSUE TITLE
Unnecessary dependencies in install_requires

### ISSUE THREAD

**Issue by musicinmybrain** [wtclarke/pymapvbvd#29]
A couple of the dependencies that `setup.py` reads from `requirements.yml` to form the `install_requires` do not really need to be runtime dependencies.

- `setuptools` is really only needed to build a wheel
- `pytest` is only used for running the tests

I don’t know much about the `requirements.yml` file, and every Python project seems to handle this differently, but would it be possible to move these out into separate `requirements.txt` style files, or add a `test` extra, so that installing the package doesn’t bring in `pytest` in particular?

**Comment by wtclarke** [comment]
Hi @musicinmybrain,

Yes, I wasn't very experienced with python packaging when I pulled this together. The setuptools dependency is now handled in the pyproject.toml file, and I'll take a look at how to do the tests dependency. The extras look like a good mechanism.

**Comment by wtclarke** [comment]
This should be sorted in 0.5.3

**Comment by musicinmybrain** [comment]
Thanks!
