### ISSUE TITLE
Wrong size when reading noise.unsorted()

### ISSUE THREAD

**Issue by p-sodmann** [wtclarke/pymapvbvd#4]
Hi, when reading a file and accessing the data with sens_object.noise.unsorted() I get an array with the size of [256,30,256]
The original Matlab code I am porting from, has a shape of [512, 30, 256]

The information below suggests, that there are 512 columns in the data?

***twix_map_obj***
File: data/[...]AdjCoilSens.dat
Software: vd
Number of acquisitions read 256
Data size is [512, 30,128,  1,  1,  2,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1]
Squeezed data size is [256,30,128,2] (['Col', 'Cha', 'Lin', 'Ave'])
NCol = 512
NCha = 30
NLin  = 128
NAve  = 2

**Comment by wtclarke** [comment]
Hi @p-sodmann,

Try setting `sens_object.noise.flagRemoveOS = False` for the time being. However, this flag should be reflected in the description of the data in a more obvious way and perhaps the default setting should be different.

**Comment by p-sodmann** [comment]
Hi,

this helped. The Flag was not raised in MatLab by default for some reason. 

Thank you for maintaining this python port!
