### ISSUE TITLE
Compatibility with Python 3.6.x

### ISSUE THREAD

**Issue by sravan953** [wtclarke/pymapvbvd#7]
Are there any Python 3.7 specific functionalities that are leveraged? If not, can the PyPI release be updated to support Python 3.6.x? Happy open a PR if that helps!

**Comment by wtclarke** [comment]
Hi @sravan953 sorry for the very slow reply. Yes please, do open a PR for that small change. I can then release a new version. I think I use dataclasses somewhere but I see the last change I made was to make sure I don't import that package for python versions >=3.7/

**Comment by wtclarke** [comment]
This should be fixed in b376613cbb5af395a592cc61391336c643585067. A new release will follow shortly.
